### ISSUE TITLE
AttributeError: 'Thread' object has no attribute 'isAlive' when running sudo python3 install.py

### ISSUE THREAD

**Issue by jramirez857** [sunfounder/vilib#3]
Hello, I am trying to get setup with my picar and am getting this error when running the installation steps from the README.

```
picar@raspberrypi:~/vilib $ sudo python3 install.py
Start installing vilib 0.0.3 for user jose
 - dpkg configure... Traceback (most recent call last):
  File "/home/picar/vilib/install.py", line 244, in <module>
    install()
  File "/home/picar/vilib/install.py", line 153, in install
    do(msg="dpkg configure",
  File "/home/picar/vilib/install.py", line 231, in do
    while _thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```
I am running with python 3.9.2 that was installed by default on my Raspbian Image. See the OS info below.

```
picar@raspberrypi:~/vilib $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
Is it possible I should be using a different python version?

**Comment by DavidCalles** [comment]
Happened the same to me, starting from python 3.9, the isAlive() method has been renamed to is_alive(). Just changing it into the file fixed it for me.

**Comment by Lovmong** [comment]
The problem has been fixed. This issue will be closed.
